FROM python:3.10-slim

WORKDIR /app

COPY ../../hello.proto .
COPY ./servidor/servidor.py .

RUN pip install grpcio grpcio-tools

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. hello.proto

EXPOSE 50051

CMD ["python", "servidor.py"]