version: '3.8'

services:
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    ports:
      - 5555:5555
      - 5556:5556
    command: ["python", "broker.py"]

  server:
    build:
      context: .
      dockerfile: server-python/Dockerfile
    depends_on:
      - broker
    command: ["python", "server.py"]
    volumes:
      - ./data:/app/data

  client:
    build:
      context: .
      dockerfile: client-java/Dockerfile
    depends_on:
      - broker
    command: ["java", "-jar", "target/client.jar"]
    deploy:
      replicas: 2

