services:
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    ports:
      - 5555:5555
      - 5556:5556
    command: ["python", "broker.py"]

  server:
    build:
      context: .
      dockerfile: server-python/Dockerfile
    depends_on:
      - broker
    command: ["python", "server.py"]
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 2

  client:
    build:
      context: .
      dockerfile: client-java/Dockerfile
    depends_on:
      - broker
    command: ["java", "-jar", "target/client.jar"]
    deploy:
      replicas: 2

  pubsub-proxy:
    build:
      context: .
      dockerfile: pub-sub/Dockerfile
    ports:
      - 5557:5557
      - 5558:5558
    command: ["python", "proxy.py"]

  heartbeat:
    build:
      context: .
      dockerfile: heartbeat/Dockerfile
    ports:
      - 6666:6666
      - 6667:6667
    command: ["python", "heartbeat.py"]